name: software-design5
version: '0.0.1'
license: GPL-3
github: kp2pml30/ifmo-labs

dependencies:
  - base
  - lens
  - with-utf8
  - mtl
  - containers
  - yada-pargen-runtime
  - transformers

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-tabs

default-extensions:
  - BlockArguments
  - BangPatterns
  - RecordWildCards
  - BlockArguments
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - OverloadedStrings
  - LambdaCase

executables:
  hw5:
    main: Main.hs
    source-dirs: .
    dependencies: []
