name:                stella
version:             0.0.1.0
license:             GPL-3
author:              "kp2pml30"
maintainer:          "kp2pml30@gmail.com"
copyright:           "2024 kp2pml30"

description:         Homework type checker for stella language

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-tabs
- -Werror=incomplete-patterns

internal-libraries:
  stella-parser:
    #extra-deps:
    #  - alex
    #  - happy
    source-dirs: gen-parser
    #extra-source-files:
    #  - src/Gen/LexSyntax.x
    #  - src/Gen/ParSyntax.y
    dependencies:
      - array
      - mtl
      - transformers
    ghc-options:
      - -w

library:
  source-dirs: src
  dependencies:
    - stella-parser
    - array
    - mtl
    - transformers
    - containers
    - disjoint-containers ==0.3.*
  default-extensions:
      - DerivingStrategies
      - LambdaCase
      - TupleSections
      - GeneralizedNewtypeDeriving
      - RecordWildCards

executables:
  stella-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stella-parser
      - stella
    default-extensions:
      - DerivingStrategies
      - LambdaCase
      - TupleSections
      - GeneralizedNewtypeDeriving
      - RecordWildCards

tests:
  stella-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stella
      - stella-parser
