hasMark(StudentId, CourseId) :-
	Marks(StudentId, CourseId, _).
good(StudentId) :-
	Students(StudentId, _, GroupId),
	Plan(GroupId, CourseId, _),
	Courses(CourseId, :CourseName).
bad(StudentId) :-
	Students(StudentId, _, GroupId),
	Plan(GroupId, CourseId, _),
	Courses(CourseId, :CourseName),
	hasMark(StudentId, CourseId).
sel(StudentId, StudentName, GroupName) :-
	Students(StudentId, StudentName, GroupId),
	Groups(GroupId, GroupName),
	good(StudentId),
	not bad(StudentId).