hasMark(StudentId, CourseId) :- Marks(StudentId, CourseId, _).
hasCourse(StudentId, CourseId) :- Students(StudentId, _, GroupId), Plan(GroupId, CourseId, _).
sel(StudentId, CourseId) :- hasCourse(StudentId, CourseId).
sel(StudentId, CourseId) :- hasMark(StudentId, CourseId), not hasCourse(StudentId, CourseId).
sel2(StudentName, CourseName) :-
	Students(StudentId, StudentName, _),
	Courses(CourseId, CourseName),
	sel(StudentId, CourseId).
	