hasMark(StudentId, CourseId) :- Marks(StudentId, CourseId, _).
hasCourse(StudentId, CourseId) :- Students(StudentId, _, GroupId), Plan(GroupId, CourseId, _).
goodMark(StudentId, CourseId) :-
    Marks(StudentId, CourseId, Mark),
    Mark > 2.
bad(StudentId, CourseId) :- hasCourse(StudentId, CourseId), not goodMark(StudentId, CourseId).
sel(StudentName, CourseName) :-
    Students(StudentId, StudentName, _),
    Courses(CourseId, CourseName),
    bad(StudentId, CourseId).